name: connection_stat
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.3 <3.0.0"

dependencies:
  dio: ^4.0.6
  # check_vpn_connection: ^0.0.2
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
